// <auto-generated />
namespace YB.Mall.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init000001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init000001));
        
        string IMigrationMetadata.Id
        {
            get { return "201610280838078_init000001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
